# Константы
CELL_WIDTH = 100
CELL_HEIGHT = 100
GRID_COLS = 7
GRID_ROWS = 6
SCREEN_WIDTH = GRID_COLS * CELL_WIDTH
SCREEN_HEIGHT = GRID_ROWS * CELL_HEIGHT

# Цвета
WHITE = "#FFFFFF"
GRID_COLOR = "#CCCCCC"
ROBOT_COLOR = "#B3BC3E"
DETAIL_COLOR = "#000000"
EYE_COLOR = "#FFFFFF"
OBSTACLE_COLOR = "#6E73F7"
TARGET_COLOR1 = "#D71F1F"
TARGET_COLOR2 = "#2BD586"